### ISSUE TITLE
Can not find the DokuWiki Package in sublime text

### ISSUE THREAD

**Issue by w3cmark** [bgx4k3p/DokuWikiSyntax#1]
hi~ I try to find you package with the following methods:
Press Ctrl + Shift + P
Select 'Install Package'
Select 'DokuWiki Syntax'

but failed! Can not find the DokuWiki
Can you tell me what 's going on? Thanks!

**Comment by bgx4k3p** [comment]
What version of Sublime Text do you have? The .sublime-syntax support has been added with build 3092. You need that or newer. Doesn't work with ST2.

**Comment by w3cmark** [comment]
Resolved, the reason is exactly the version of the problem.
Thanks!
